---
lint: |
  set -e
  yamllint .
  ansible-lint -f full
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: lpar2rrd-rhel9
    pre_build_image: false
    image: registry.hub.docker.com/redhat/ubi9-init:latest  # renovate: datasource=docker
    privileged: true
    command: "/usr/sbin/init"

provisioner:
  name: ansible
  playbooks:
    converge: ../shared_files/converge.yml
    prepare: ../shared_files/prepare.yml
verifier:
  name: ansible
