---
- name: add group - {{ lpar2rrd_group }}
  ansible.builtin.group:
    name: "{{ lpar2rrd_group }}"
    state: present

- name: add user - {{ lpar2rrd_user }}
  ansible.builtin.user:
    name: "{{ lpar2rrd_user }}"
    group: "{{ lpar2rrd_group }}"
    shell: "{{ lpar2rrd_shell }}"
    state: present

- name: install dependecies
  ansible.builtin.package:
    name: "{{ lpar2rrd_dependecies }}"
    state: present

- name: create temporary download directory
  ansible.builtin.tempfile:
    state: directory
    suffix: download_lpar2rrd
  register: download_dir

- name: download url
  set_fact:
    download_url: "{{ lpar2rrd_baseurl }}/lpar2rrd-agent{{ __lpar2rrd_delimiter }}{{ lpar2rrd_version }}{{ __lpar2rrd_arch }}.{{ __lpar2rrd_type }}"

- name: download filename
  set_fact:
    download_filename: "{{ download_dir.path }}/package.{{ __lpar2rrd_type }}"

- name: debug
  debug:
    var: download_url
  when: debug | bool

- name: debug
  debug:
    var: download_filename
  when: debug | bool

- name: download file
  ansible.builtin.get_url:
    url: "{{ download_url }}"
    dest: "{{ download_filename }}"
    validate_certs: no

- name: apt -install lpar2rrd {{ lpar2rrd_version }}
  ansible.builtin.apt:
    deb: "{{ download_filename }}"
    allow_unauthenticated: yes
    state: present
  when: ansible_pkg_mgr in ['apt']

- name: dnf/yum -install lpar2rrd {{ lpar2rrd_version }}
  ansible.builtin.yum:
    name: "{{ download_filename }}"
    disable_gpg_check: yes
    state: present
  when: ansible_pkg_mgr in ['dnf', 'yum']

- name: setup crontab entry for {{ lpar2rrd_user }}
  ansible.builtin.cron:
    name: "{{ lpar2rrd_user }}"
    user: "{{ lpar2rrd_user }}"
    job: "{{ lpar2rrd_crontab_job }}"
    minute: "{{ lpar2rrd_crontab_minute }}"
    hour: "{{ lpar2rrd_crontab_hour }}"
    day: "{{ lpar2rrd_crontab_day }}"
    month: "{{ lpar2rrd_crontab_month }}"
    weekday: "{{ lpar2rrd_crontab_weekday  }}"
    state: present

- name: remove tempdir
  ansible.builtin.file:
    path: "{{ download_dir.path }}"
    state: absent
  when:
    - download_dir.path is defined
    - not debug | bool
