---
lint: |
  set -e
  yamllint .
  ansible-lint -f full
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: lpar2rrd-rhel10
    pre_build_image: false
    # renovate: datasource=docker depName=registry.access.redhat.com/ubi9/ubi-init
    image: registry.access.redhat.com/ubi10/ubi-init:latest
    privileged: true
    command: "/usr/sbin/init"
    # groups:
    #   - rhel9

provisioner:
  name: ansible
  playbooks:
    converge: ../shared_files/converge.yml
    prepare: ../shared_files/prepare.yml
verifier:
  name: ansible
