---
lint: |
  set -e
  yamllint .
  ansible-lint -f rich
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: lpar2rrd-rhel8
    pre_build_image: false
    registry:
      url: registry.access.redhat.com
    image: ubi8/ubi-init
    privileged: true
    command: "/usr/sbin/init"

provisioner:
  name: ansible
verifier:
  name: ansible
