---
lint: |
  set -e
  yamllint .
  ansible-lint -f rich
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: lpar2rrd-rhel
    image: registry.access.redhat.com/ubi8/ubi-init
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: "/sbin/init"

provisioner:
  name: ansible
verifier:
  name: ansible
