---
- name: Ensure we all the dependecies
  hosts: all
  gather_facts: true
  tasks:
    - name: rhel deps
      ansible.builtin.package:
        name:
          - crontabs
        state: present
      when: ansible_facts['distribution'] in ['RedHat']

    - name: deb deps
      ansible.builtin.apt:
        name:
          - cron
          - procps
        update_cache: yes
        state: present
      when: ansible_facts['distribution'] in ['Debian']

    - name: rhel- start cron service
      ansible.builtin.service:
        name: crond
        enabled: yes
        state: started
      when: ansible_facts['distribution'] in ['RedHat']

    - name: deb - start cron service
      ansible.builtin.service:
        name: cron
        enabled: yes
        state: started
      when: ansible_facts['distribution'] in ['Debian']
