---
- name: Ensure we all the dependecies
  hosts: all
  gather_facts: true
  tasks:
    - name: rhel
      block:
        - name: rhel deps
          ansible.builtin.package:
            name:
              - crontabs
            state: present

        - name: rhel- start cron service
          ansible.builtin.service:
            name: crond
            enabled: yes
            state: started
      when: ansible_facts['distribution'] in ['RedHat']

    - name: debian
      block:
        - name: deb deps
          ansible.builtin.apt:
            name:
              - cron
              - procps
            update_cache: yes
            state: present
        - name: deb - start cron service
          ansible.builtin.service:
            name: cron
            enabled: yes
            state: started
      when: ansible_facts['distribution'] in ['Debian']
