---
- name: Prepare RH instances
  hosts: rhel
  gather_facts: false
  tasks:
    - name: RH - fix /etc/shadow permissions
      ansible.builtin.raw: chmod 0400 /etc/shadow

# - name: Prepare RH8 instances
#   hosts: rhel8
#   gather_facts: false
#   tasks:
#     - name: RH8 - install python3.11
#       # ansible.builtin.raw: yum -y install python3.9 python3.11 python3.11-pip python3-dnf
#       ansible.builtin.raw: yum -y install python3-dnf

#     - name: Setup python3 as default python
#       ansible.builtin.command: "{{ item }}"
#       register: alt_output
#       loop:
#         - "alternatives --list"
#         - "alternatives --set python3 /usr/bin/python3.11"
#         # - "python3 -m pip install python-dnf"
#         - "ls -l /usr/bin/python3"
#         - "ls -l /etc/alternatives/python3"

#     - name: Debug output
#       ansible.builtin.debug:
#         var: item.stdout_lines
#       loop: "{{ alt_output.results }}"

- name: Ensure we all the dependecies
  hosts: all
  gather_facts: true
  tasks:
    - name: Rhel
      when: ansible_facts['distribution'] in ['RedHat']
      block:
        - name: Rhel deps
          ansible.builtin.package:
            name:
              - crontabs
              - cronie
            state: present

        - name: Rhel- start cron service
          ansible.builtin.service:
            name: crond
            enabled: yes
            state: started


    - name: Debian
      when: ansible_facts['distribution'] in ['Debian']
      block:
        - name: Deb deps
          ansible.builtin.apt:
            name:
              - cron
              - procps
            update_cache: yes
            state: present
        - name: Deb - start cron service
          ansible.builtin.service:
            name: cron
            enabled: yes
            state: started
