---
lint: |
  set -e
  yamllint .
  ansible-lint -f full
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: lpar2rrd-debian-stable
    pre_build_image: false
    image: registry.hub.docker.com/library/debian:stable # renovate datasource=docker
    dockerfile: template-Dockerfile-debian.j2
    privileged: true
    command: "/sbin/init"

provisioner:
  name: ansible
  playbooks:
    converge: ../shared_files/converge.yml
    prepare: ../shared_files/prepare.yml
verifier:
  name: ansible
