name: Molecule

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - rhel9
          - rhel10
          - debian
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          path: "${{ github.repository }}"

      - name: Molecule
        uses: gofrolist/molecule-action@f6757af16d4781d4d9c21e93ef593f5fa0895fa5 # v2
        with:
          molecule_args: --scenario-name ${{ matrix.scenario }}
