---
lint: |
  set -e
  yamllint .
  # ansible-lint -f rich
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: lpar2rrd-rhel8
    pre_build_image: false
    registry:
      url: registry.access.redhat.com
    image: ubi8/ubi-init
    privileged: true
    command: "/usr/sbin/init"

provisioner:
  name: ansible
  playbooks:
    converge: install_remove.yml
    prepare: ../default/prepare.yml
verifier:
  name: ansible
